language: php

php: 
  - 5.4
#  - 5.5
  - 5.6
#  - 7
#  - hhvm
#  - hhvm-nightly
  
matrix:
    fast_finish: true
    allow_failures:
      - php: hhvm-nightly
      - php: 7.0
    
before_script:
#  - chmod 777 ./tests/travis/setup_arangodb.sh
#  - ./tests/travis/setup_arangodb.sh
  - bash tests/before.sh
  - composer install --prefer-source --no-interaction --dev


after_script:
 - php vendor/bin/coveralls -v

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

addons:
  hosts:
    - db-link