language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
    
before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh
  - bash tests/before.sh
  - composer install --prefer-source --no-interaction --dev


after_script:
  # - php vendor/bin/coveralls
  # or enable logging
 - php vendor/bin/coveralls -v

script:
 - mkdir -p build/logs
 - phpunit --testsuite ArangoDB-PHP-Core --coverage-clover build/logs/clover.xml

