language: php

php: 
  - 7.0
  - 7.1
  - hhvm-3.15
  #  - hhvm-nightly

dist: xenial

matrix:
    fast_finish: true
#    allow_failures:
#      - php: hhvm-nightly
#      - php: 7.1

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require --dev --no-update phpunit/phpunit 6.*; else composer require --dev --no-update phpunit/phpunit ~5; fi

install:
  - travis_retry composer install --prefer-source --no-interaction --dev --ignore-platform-reqs

before_script:
  - bash tests/before.sh
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs
  - composer dumpautoload -o

after_script:
  - php vendor/bin/coveralls -v

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

addons:
  hosts:
    - db-link
    