language: php

php: 
  - 5.3
  - 5.4
  - 5.5

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh
  - bash tests/before.sh


after_script:
  # - php vendor/bin/coveralls
  # or enable logging
 - php vendor/bin/coveralls -v

script:
 - mkdir -p build/logs
 - phpunit --configuration ./tests/phpunit.xml --testsuite ArangoDB-PHP-Core --coverage-clover build/logs/clover.xml

