language: php

php: 
  - 7.0
  - 7.1
  - hhvm-3.18
  #  - hhvm-nightly

dist: trusty

sudo: required

matrix:
    fast_finish: true
#    allow_failures:
#      - php: hhvm-nightly

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require --dev --no-update phpunit/phpunit 6.*; else composer require --dev --no-update phpunit/phpunit ~5; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
before_script:
#  - bash tests/before.sh
  - composer install --prefer-source --no-interaction --ignore-platform-reqs
  - composer dumpautoload -o

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)